version: '3.8'

services:
  # Backend (Node.js + Express)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file: ./.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Frontend (React + Webpack)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped